import HautevilleHouse.CrystallographyAperiodicCrystalsCanonicalLaneLean.AperiodicCrystalStructures
import HautevilleHouse.CrystallographyAperiodicCrystalsCanonicalLaneLean.QuasicrystalClassification
import HautevilleHouse.CrystallographyAperiodicCrystalsCanonicalLaneLean.DiffractionPatternAnalysis
import HautevilleHouse.CrystallographyAperiodicCrystalsCanonicalLaneLean.SuperspaceEmbedding
import HautevilleHouse.CrystallographyAperiodicCrystalsCanonicalLaneLean.TilingDynamics

namespace HautevilleHouse
namespace CrystallographyAperiodicCrystalsCanonicalLaneLean

-- This file aggregates all domain-specific modules.

end CrystallographyAperiodicCrystalsCanonicalLaneLean
end HautevilleHouse
